server:
  port: 8888
spring:
  application:
    name: config-server
---

spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Projects/GMP/config-repo

---

spring:
  profiles: container
  cloud:
      config:
        server:
          git:
            uri: file://config-repo